import { GoogleGenAI } from "@google/genai";
import { Resolution } from "../types";

const getClient = () => {
  const apiKey = process.env.API_KEY;
  if (!apiKey) {
    throw new Error("API Key not found in environment variables");
  }
  return new GoogleGenAI({ apiKey });
};

export const generateSeparatedImage = async (
  base64Data: string, 
  mimeType: string, 
  prompt: string,
  resolution: Resolution
): Promise<string> => {
  const ai = getClient();
  
  // Clean base64 string if it contains the data url prefix
  const cleanBase64 = base64Data.replace(/^data:image\/(png|jpeg|jpg|webp);base64,/, '');

  let model = 'gemini-2.5-flash-image';
  let config: any = {};

  // Determine model and config based on resolution
  switch (resolution) {
    case '1240p':
    case '1440p':
    case '2K':
      model = 'gemini-3-pro-image-preview';
      config = {
        imageConfig: {
          imageSize: '2K'
        }
      };
      break;
    case '4K':
    case '8K':
      model = 'gemini-3-pro-image-preview';
      config = {
        imageConfig: {
          imageSize: '4K'
        }
      };
      break;
    case '480p':
    case '720p':
    case '1040p':
    default:
      model = 'gemini-2.5-flash-image';
      // Flash model does not support imageSize config for editing in the same way
      break;
  }

  try {
    const response = await ai.models.generateContent({
      model: model,
      contents: {
        parts: [
          {
            inlineData: {
              data: cleanBase64,
              mimeType: mimeType,
            },
          },
          {
            text: prompt,
          },
        ],
      },
      config: config
    });

    // Iterate through parts to find the image
    const candidates = response.candidates;
    if (candidates && candidates.length > 0) {
      const parts = candidates[0].content.parts;
      for (const part of parts) {
        if (part.inlineData && part.inlineData.data) {
          return `data:image/png;base64,${part.inlineData.data}`;
        }
      }
    }

    throw new Error("No image generated by the model.");
  } catch (error) {
    console.error("Gemini API Error:", error);
    throw error;
  }
};

export const generateArtisticImage = async (
    base64Data: string,
    mimeType: string,
    options: {
        style: string;
        detailLevel: number; // 0-100
        creativity: number; // 0-100
        customPrompt?: string;
    }
): Promise<string> => {
    const ai = getClient();
    const cleanBase64 = base64Data.replace(/^data:image\/(png|jpeg|jpg|webp);base64,/, '');

    // Construct prompt based on settings
    const prompt = `
        You are a master digital artist. Transform this input image into a high-quality artwork.
        Style: ${options.style}.
        Level of Detail: ${options.detailLevel}% (where 100% is hyper-realistic and intricate).
        Creativity/Deviation: ${options.creativity}% (where 100% is very abstract/imaginative, 0% is exact copy).
        Custom Instructions: ${options.customPrompt || 'None'}.
        
        Requirements:
        1. Maintain the main subject and composition of the original image.
        2. Apply the requested artistic style meticulously.
        3. Ensure 99% detail accuracy in textures and lighting.
        4. Output only the image.
    `;

    // Use the pro model for best artistic results
    const model = 'gemini-3-pro-image-preview'; 
    const config = {
        imageConfig: {
            imageSize: '2K' // High quality output
        }
    };

    try {
        const response = await ai.models.generateContent({
            model: model,
            contents: {
                parts: [
                    { inlineData: { data: cleanBase64, mimeType: mimeType } },
                    { text: prompt }
                ]
            },
            config: config
        });

        const candidates = response.candidates;
        if (candidates && candidates.length > 0) {
            const parts = candidates[0].content.parts;
            for (const part of parts) {
                if (part.inlineData && part.inlineData.data) {
                    return `data:image/png;base64,${part.inlineData.data}`;
                }
            }
        }
        throw new Error("No artistic image generated.");
    } catch (error) {
        console.error("Artistic Gen Error:", error);
        throw error;
    }
};
